Fix #263: update to unicode 8.0.0. Also remove esutils.
shapesecurity/shift-parser-js pull request #342
Opened 2017-03-06 21:54 UTC by bakkot

esutils has not published a version with 8.0.0, so replace the parts of it we need with an in-house version.

2017-03-07 18:57 UTC, michaelficarra reviewed
Are we okay using Set and Array#fill? If we're using Set, would checking set inclusion be faster than the regexp?

2017-03-07 18:57 UTC, michaelficarra commented on scripts/generate-unicode-data.js
> +let whitespace = [0x09, 0x0B, 0x0c, 0x20, 0xA0, 0xFEFF].concat(require(`unicode-${unicodeVersion}/General_Category/Space_Separator/code-points`));
What's the point of including these when we're just going to filter them out?

2017-03-07 18:57 UTC, michaelficarra commented on scripts/generate-unicode-data.js
> +let lineTerminators = [0x0A, 0x0D, 0x2028, 0x2029];
This appears unused.

2017-03-07 19:00 UTC, bakkot commented
> Are we okay using Set and Array#fill? If we're using Set, would checking set inclusion be faster than the regexp?

We are (node 4, woo!), but it's not faster. I checked.

2017-03-07 19:01 UTC, bakkot commented on scripts/generate-unicode-data.js
> +let whitespace = [0x09, 0x0B, 0x0c, 0x20, 0xA0, 0xFEFF].concat(require(`unicode-${unicodeVersion}/General_Category/Space_Separator/code-points`));
Eh... the idea was that this is all of the whitespace. But sure, I can remove them.

2017-03-07 19:01 UTC, bakkot commented on scripts/generate-unicode-data.js
> +let lineTerminators = [0x0A, 0x0D, 0x2028, 0x2029];
Whoops. Leftover code from a previous iteration.

2017-03-07 19:53 UTC, michaelficarra commented on scripts/generate-unicode-data.js
> +console.log(`// Generated by scripts/generate-unicode-data.js
Generate this name from `__filename`?

2017-03-08 19:11 UTC, bakkot commented
@michaelficarra addressed comments.

2017-03-09 16:00 UTC, michaelficarra requested changes

2017-03-09 16:00 UTC, michaelficarra commented on src/utils.js
> +  return ch === 0x20 || ch === 0x09 || ch === 0x0B || ch === 0x0C || ch === 0xA0 || ch > 0x167F && whitespaceArray.indexOf(ch) !== -1;
I would prefer that this function mirrored `isIdentifierStart`.

2017-03-09 19:22 UTC, bakkot commented on src/utils.js
> +  return ch === 0x20 || ch === 0x09 || ch === 0x0B || ch === 0x0C || ch === 0xA0 || ch > 0x167F && whitespaceArray.indexOf(ch) !== -1;
Done, kind of.

2017-03-10 03:42 UTC, michaelficarra approved these changes

2017-03-14 21:10 UTC, merged